name: xarray-weather-server
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.13
  # Scientific Computing Stack
  - xarray>=2025.1.2
  - numpy>=1.24.3
  - pandas>=2.1.4
  - zarr>=3.0.4
  # Web Framework
  - fastapi>=0.104.1
  - uvicorn>=0.24.0
  # Image Processing
  - pillow>=10.1.0
  # File System & Cloud Storage
  - fsspec>=2023.12.2
  - gcsfs>=2023.12.2
  # Development Dependencies
  - requests>=2.31.0
  - pytest>=7.4.0
  - black>=23.0.0
  - flake8>=6.0.0